PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
CREATE TABLE Acciones(id_accion INTEGER PRIMARY KEY, titulo TEXT NOT NULL, descripcion TEXT NOT NULL, categoria TEXT NOT NULL, dificultad TEXT NOT NULL CHECK(dificultad IN ('Baja','Media')), id_contenido INTEGER NOT NULL REFERENCES Contenidos(id_contenido));
INSERT INTO "Acciones" VALUES(1,'Apagar luces innecesarias','Apagar la iluminación de ambientes desocupados.','Hogar','Baja',6);
INSERT INTO "Acciones" VALUES(2,'Aprovechar la luz natural','Usar la iluminación natural cuando sea suficiente.','Hogar','Baja',6);
INSERT INTO "Acciones" VALUES(3,'Elegir lámparas LED','Considerar LED al reemplazar lámparas.','Hogar','Media',6);
INSERT INTO "Acciones" VALUES(4,'Usar transporte público','Evaluar esta opción cuando el recorrido y la disponibilidad lo permitan.','Movilidad','Media',6);
CREATE TABLE ContenidoFuente(id_contenido INTEGER NOT NULL REFERENCES Contenidos(id_contenido), id_fuente INTEGER NOT NULL REFERENCES Fuentes(id_fuente), PRIMARY KEY(id_contenido,id_fuente));
INSERT INTO "ContenidoFuente" VALUES(1,1);
INSERT INTO "ContenidoFuente" VALUES(2,1);
INSERT INTO "ContenidoFuente" VALUES(3,1);
INSERT INTO "ContenidoFuente" VALUES(4,1);
INSERT INTO "ContenidoFuente" VALUES(5,2);
INSERT INTO "ContenidoFuente" VALUES(6,3);
CREATE TABLE Contenidos(id_contenido INTEGER PRIMARY KEY, titulo TEXT NOT NULL CHECK(length(trim(titulo))>0), texto TEXT NOT NULL, seccion TEXT NOT NULL, fecha_actualizacion TEXT NOT NULL, id_tipo INTEGER REFERENCES TiposEnergia(id_tipo));
INSERT INTO "Contenidos" VALUES(1,'Solar','Aprovecha la radiación solar para obtener calor o electricidad.','Fuentes renovables','2026-09-27',1);
INSERT INTO "Contenidos" VALUES(2,'Eólica','Transforma la energía del viento en energía mecánica o eléctrica.','Fuentes renovables','2026-09-27',2);
INSERT INTO "Contenidos" VALUES(3,'Hidroeléctrica','Aprovecha el movimiento o desnivel del agua para generar electricidad.','Fuentes renovables','2026-09-27',3);
INSERT INTO "Contenidos" VALUES(4,'Biomasa','Utiliza materia orgánica como recurso energético.','Fuentes renovables','2026-09-27',4);
INSERT INTO "Contenidos" VALUES(5,'Energía y clima','La transición energética combina fuentes renovables, eficiencia e inversión en infraestructura.','El problema','2026-09-27',NULL);
INSERT INTO "Contenidos" VALUES(6,'Acciones cotidianas','Podemos reducir consumos innecesarios y elegir opciones de movilidad según nuestras posibilidades.','Cómo ayudar','2026-09-27',NULL);
CREATE TABLE Fuentes(id_fuente INTEGER PRIMARY KEY, organismo TEXT NOT NULL, titulo TEXT NOT NULL, url TEXT NOT NULL UNIQUE, fecha_consulta TEXT NOT NULL);
INSERT INTO "Fuentes" VALUES(1,'Argentina.gob.ar','Qué son las energías renovables','https://www.argentina.gob.ar/economia/energia/energia-electrica/renovables/que-son-las-energias-renovables','2026-09-27');
INSERT INTO "Fuentes" VALUES(2,'Naciones Unidas','Energías renovables para un futuro más seguro','https://www.un.org/es/climatechange/raising-ambition/renewable-energy','2026-09-27');
INSERT INTO "Fuentes" VALUES(3,'Naciones Unidas','Acciones por un planeta saludable','https://www.un.org/es/actnow/ten-actions','2026-09-27');
CREATE TABLE TiposEnergia(id_tipo INTEGER PRIMARY KEY, nombre TEXT NOT NULL UNIQUE, descripcion TEXT NOT NULL, recurso_principal TEXT NOT NULL);
INSERT INTO "TiposEnergia" VALUES(1,'Solar','Aprovecha la radiación solar para obtener calor o electricidad.','Sol');
INSERT INTO "TiposEnergia" VALUES(2,'Eólica','Transforma la energía del viento en energía mecánica o eléctrica.','Viento');
INSERT INTO "TiposEnergia" VALUES(3,'Hidroeléctrica','Aprovecha el movimiento o desnivel del agua para generar electricidad.','Agua');
INSERT INTO "TiposEnergia" VALUES(4,'Biomasa','Utiliza materia orgánica como recurso energético.','Materia orgánica');
COMMIT;
PRAGMA foreign_keys = ON;
PRAGMA foreign_key_check;
